package top.fluffcotton.pojo;

public class FolderGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder_group.fileId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String fileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder_group.folderId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String folderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder_group.groupId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder_group.childrenId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String childrenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder_group.deleteTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long deletetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder_group.fileId
     *
     * @return the value of folder_group.fileId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder_group.fileId
     *
     * @param fileid the value for folder_group.fileId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setFileid(String fileid) {
        this.fileid = fileid == null ? null : fileid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder_group.folderId
     *
     * @return the value of folder_group.folderId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getFolderid() {
        return folderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder_group.folderId
     *
     * @param folderid the value for folder_group.folderId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setFolderid(String folderid) {
        this.folderid = folderid == null ? null : folderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder_group.groupId
     *
     * @return the value of folder_group.groupId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder_group.groupId
     *
     * @param groupid the value for folder_group.groupId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder_group.childrenId
     *
     * @return the value of folder_group.childrenId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getChildrenid() {
        return childrenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder_group.childrenId
     *
     * @param childrenid the value for folder_group.childrenId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setChildrenid(String childrenid) {
        this.childrenid = childrenid == null ? null : childrenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder_group.deleteTime
     *
     * @return the value of folder_group.deleteTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getDeletetime() {
        return deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder_group.deleteTime
     *
     * @param deletetime the value for folder_group.deleteTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setDeletetime(Long deletetime) {
        this.deletetime = deletetime;
    }
}