package top.fluffcotton.pojo;

public class Folder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.fileId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String fileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.fileName
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.userID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.isRoot
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Boolean isroot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.deleteTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long deletetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.fileId
     *
     * @return the value of folder.fileId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.fileId
     *
     * @param fileid the value for folder.fileId
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setFileid(String fileid) {
        this.fileid = fileid == null ? null : fileid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.fileName
     *
     * @return the value of folder.fileName
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.fileName
     *
     * @param filename the value for folder.fileName
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.userID
     *
     * @return the value of folder.userID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.userID
     *
     * @param userid the value for folder.userID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.isRoot
     *
     * @return the value of folder.isRoot
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Boolean getIsroot() {
        return isroot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.isRoot
     *
     * @param isroot the value for folder.isRoot
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setIsroot(Boolean isroot) {
        this.isroot = isroot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.deleteTime
     *
     * @return the value of folder.deleteTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getDeletetime() {
        return deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.deleteTime
     *
     * @param deletetime the value for folder.deleteTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setDeletetime(Long deletetime) {
        this.deletetime = deletetime;
    }
}