package top.fluffcotton.pojo;

import java.util.ArrayList;
import java.util.List;

public class GroupFunctionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public GroupFunctionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGroupidIsNull() {
            addCriterion("groupID is null");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNotNull() {
            addCriterion("groupID is not null");
            return (Criteria) this;
        }

        public Criteria andGroupidEqualTo(String value) {
            addCriterion("groupID =", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotEqualTo(String value) {
            addCriterion("groupID <>", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThan(String value) {
            addCriterion("groupID >", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThanOrEqualTo(String value) {
            addCriterion("groupID >=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThan(String value) {
            addCriterion("groupID <", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThanOrEqualTo(String value) {
            addCriterion("groupID <=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLike(String value) {
            addCriterion("groupID like", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotLike(String value) {
            addCriterion("groupID not like", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidIn(List<String> values) {
            addCriterion("groupID in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotIn(List<String> values) {
            addCriterion("groupID not in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidBetween(String value1, String value2) {
            addCriterion("groupID between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotBetween(String value1, String value2) {
            addCriterion("groupID not between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andCommandIsNull() {
            addCriterion("command is null");
            return (Criteria) this;
        }

        public Criteria andCommandIsNotNull() {
            addCriterion("command is not null");
            return (Criteria) this;
        }

        public Criteria andCommandEqualTo(Boolean value) {
            addCriterion("command =", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotEqualTo(Boolean value) {
            addCriterion("command <>", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandGreaterThan(Boolean value) {
            addCriterion("command >", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandGreaterThanOrEqualTo(Boolean value) {
            addCriterion("command >=", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandLessThan(Boolean value) {
            addCriterion("command <", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandLessThanOrEqualTo(Boolean value) {
            addCriterion("command <=", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandIn(List<Boolean> values) {
            addCriterion("command in", values, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotIn(List<Boolean> values) {
            addCriterion("command not in", values, "command");
            return (Criteria) this;
        }

        public Criteria andCommandBetween(Boolean value1, Boolean value2) {
            addCriterion("command between", value1, value2, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotBetween(Boolean value1, Boolean value2) {
            addCriterion("command not between", value1, value2, "command");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestIsNull() {
            addCriterion("acceptGroupRequest is null");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestIsNotNull() {
            addCriterion("acceptGroupRequest is not null");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestEqualTo(Byte value) {
            addCriterion("acceptGroupRequest =", value, "acceptgrouprequest");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestNotEqualTo(Byte value) {
            addCriterion("acceptGroupRequest <>", value, "acceptgrouprequest");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestGreaterThan(Byte value) {
            addCriterion("acceptGroupRequest >", value, "acceptgrouprequest");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestGreaterThanOrEqualTo(Byte value) {
            addCriterion("acceptGroupRequest >=", value, "acceptgrouprequest");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestLessThan(Byte value) {
            addCriterion("acceptGroupRequest <", value, "acceptgrouprequest");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestLessThanOrEqualTo(Byte value) {
            addCriterion("acceptGroupRequest <=", value, "acceptgrouprequest");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestIn(List<Byte> values) {
            addCriterion("acceptGroupRequest in", values, "acceptgrouprequest");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestNotIn(List<Byte> values) {
            addCriterion("acceptGroupRequest not in", values, "acceptgrouprequest");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestBetween(Byte value1, Byte value2) {
            addCriterion("acceptGroupRequest between", value1, value2, "acceptgrouprequest");
            return (Criteria) this;
        }

        public Criteria andAcceptgrouprequestNotBetween(Byte value1, Byte value2) {
            addCriterion("acceptGroupRequest not between", value1, value2, "acceptgrouprequest");
            return (Criteria) this;
        }

        public Criteria andCheckmsgIsNull() {
            addCriterion("checkMsg is null");
            return (Criteria) this;
        }

        public Criteria andCheckmsgIsNotNull() {
            addCriterion("checkMsg is not null");
            return (Criteria) this;
        }

        public Criteria andCheckmsgEqualTo(Boolean value) {
            addCriterion("checkMsg =", value, "checkmsg");
            return (Criteria) this;
        }

        public Criteria andCheckmsgNotEqualTo(Boolean value) {
            addCriterion("checkMsg <>", value, "checkmsg");
            return (Criteria) this;
        }

        public Criteria andCheckmsgGreaterThan(Boolean value) {
            addCriterion("checkMsg >", value, "checkmsg");
            return (Criteria) this;
        }

        public Criteria andCheckmsgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("checkMsg >=", value, "checkmsg");
            return (Criteria) this;
        }

        public Criteria andCheckmsgLessThan(Boolean value) {
            addCriterion("checkMsg <", value, "checkmsg");
            return (Criteria) this;
        }

        public Criteria andCheckmsgLessThanOrEqualTo(Boolean value) {
            addCriterion("checkMsg <=", value, "checkmsg");
            return (Criteria) this;
        }

        public Criteria andCheckmsgIn(List<Boolean> values) {
            addCriterion("checkMsg in", values, "checkmsg");
            return (Criteria) this;
        }

        public Criteria andCheckmsgNotIn(List<Boolean> values) {
            addCriterion("checkMsg not in", values, "checkmsg");
            return (Criteria) this;
        }

        public Criteria andCheckmsgBetween(Boolean value1, Boolean value2) {
            addCriterion("checkMsg between", value1, value2, "checkmsg");
            return (Criteria) this;
        }

        public Criteria andCheckmsgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("checkMsg not between", value1, value2, "checkmsg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group_function
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 14 19:04:24 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group_function
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public static class Criterion {
        private final String condition;
        private final String typeHandler;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}