package top.fluffcotton.pojo;

public class GroupUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.userID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.groupID
     *
     * @return the value of group_user.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.groupID
     *
     * @param groupid the value for group_user.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.userID
     *
     * @return the value of group_user.userID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.userID
     *
     * @param userid the value for group_user.userID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}