package top.fluffcotton.pojo;

public class GroupFunction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_function.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_function.command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Boolean command;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_function.acceptGroupRequest
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Byte acceptgrouprequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_function.checkMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Boolean checkmsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_function.groupID
     *
     * @return the value of group_function.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_function.groupID
     *
     * @param groupid the value for group_function.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_function.command
     *
     * @return the value of group_function.command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Boolean getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_function.command
     *
     * @param command the value for group_function.command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setCommand(Boolean command) {
        this.command = command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_function.acceptGroupRequest
     *
     * @return the value of group_function.acceptGroupRequest
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Byte getAcceptgrouprequest() {
        return acceptgrouprequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_function.acceptGroupRequest
     *
     * @param acceptgrouprequest the value for group_function.acceptGroupRequest
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setAcceptgrouprequest(Byte acceptgrouprequest) {
        this.acceptgrouprequest = acceptgrouprequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_function.checkMsg
     *
     * @return the value of group_function.checkMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Boolean getCheckmsg() {
        return checkmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_function.checkMsg
     *
     * @param checkmsg the value for group_function.checkMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setCheckmsg(Boolean checkmsg) {
        this.checkmsg = checkmsg;
    }
}