package top.fluffcotton.pojo;

public class Mission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.M_ID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.name
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.isPrivate
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Boolean isprivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.startTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.endTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.Msg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.endMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String endmsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.Regex
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String regex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.Reply
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String reply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.remindMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String remindmsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.remindIsPrivate
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Boolean remindisprivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.remindTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long remindtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.saveMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String savemsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.status
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.groupList
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String grouplist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.M_ID
     *
     * @return the value of mission.M_ID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.M_ID
     *
     * @param mId the value for mission.M_ID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setmId(String mId) {
        this.mId = mId == null ? null : mId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.name
     *
     * @return the value of mission.name
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.name
     *
     * @param name the value for mission.name
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.isPrivate
     *
     * @return the value of mission.isPrivate
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Boolean getIsprivate() {
        return isprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.isPrivate
     *
     * @param isprivate the value for mission.isPrivate
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setIsprivate(Boolean isprivate) {
        this.isprivate = isprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.startTime
     *
     * @return the value of mission.startTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.startTime
     *
     * @param starttime the value for mission.startTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setStarttime(Long starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.endTime
     *
     * @return the value of mission.endTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.endTime
     *
     * @param endtime the value for mission.endTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setEndtime(Long endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.Msg
     *
     * @return the value of mission.Msg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.Msg
     *
     * @param msg the value for mission.Msg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.endMsg
     *
     * @return the value of mission.endMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getEndmsg() {
        return endmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.endMsg
     *
     * @param endmsg the value for mission.endMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setEndmsg(String endmsg) {
        this.endmsg = endmsg == null ? null : endmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.Regex
     *
     * @return the value of mission.Regex
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getRegex() {
        return regex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.Regex
     *
     * @param regex the value for mission.Regex
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setRegex(String regex) {
        this.regex = regex == null ? null : regex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.Reply
     *
     * @return the value of mission.Reply
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.Reply
     *
     * @param reply the value for mission.Reply
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.remindMsg
     *
     * @return the value of mission.remindMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getRemindmsg() {
        return remindmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.remindMsg
     *
     * @param remindmsg the value for mission.remindMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setRemindmsg(String remindmsg) {
        this.remindmsg = remindmsg == null ? null : remindmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.remindIsPrivate
     *
     * @return the value of mission.remindIsPrivate
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Boolean getRemindisprivate() {
        return remindisprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.remindIsPrivate
     *
     * @param remindisprivate the value for mission.remindIsPrivate
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setRemindisprivate(Boolean remindisprivate) {
        this.remindisprivate = remindisprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.remindTime
     *
     * @return the value of mission.remindTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getRemindtime() {
        return remindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.remindTime
     *
     * @param remindtime the value for mission.remindTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setRemindtime(Long remindtime) {
        this.remindtime = remindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.saveMsg
     *
     * @return the value of mission.saveMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getSavemsg() {
        return savemsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.saveMsg
     *
     * @param savemsg the value for mission.saveMsg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setSavemsg(String savemsg) {
        this.savemsg = savemsg == null ? null : savemsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.groupID
     *
     * @return the value of mission.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.groupID
     *
     * @param groupid the value for mission.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.status
     *
     * @return the value of mission.status
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.status
     *
     * @param status the value for mission.status
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.groupList
     *
     * @return the value of mission.groupList
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getGrouplist() {
        return grouplist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.groupList
     *
     * @param grouplist the value for mission.groupList
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setGrouplist(String grouplist) {
        this.grouplist = grouplist == null ? null : grouplist.trim();
    }
}