package top.fluffcotton.pojo;

import java.util.ArrayList;
import java.util.List;

public class MissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public MissionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMIdIsNull() {
            addCriterion("M_ID is null");
            return (Criteria) this;
        }

        public Criteria andMIdIsNotNull() {
            addCriterion("M_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMIdEqualTo(String value) {
            addCriterion("M_ID =", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotEqualTo(String value) {
            addCriterion("M_ID <>", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdGreaterThan(String value) {
            addCriterion("M_ID >", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdGreaterThanOrEqualTo(String value) {
            addCriterion("M_ID >=", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdLessThan(String value) {
            addCriterion("M_ID <", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdLessThanOrEqualTo(String value) {
            addCriterion("M_ID <=", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdLike(String value) {
            addCriterion("M_ID like", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotLike(String value) {
            addCriterion("M_ID not like", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdIn(List<String> values) {
            addCriterion("M_ID in", values, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotIn(List<String> values) {
            addCriterion("M_ID not in", values, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdBetween(String value1, String value2) {
            addCriterion("M_ID between", value1, value2, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotBetween(String value1, String value2) {
            addCriterion("M_ID not between", value1, value2, "mId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIsprivateIsNull() {
            addCriterion("isPrivate is null");
            return (Criteria) this;
        }

        public Criteria andIsprivateIsNotNull() {
            addCriterion("isPrivate is not null");
            return (Criteria) this;
        }

        public Criteria andIsprivateEqualTo(Boolean value) {
            addCriterion("isPrivate =", value, "isprivate");
            return (Criteria) this;
        }

        public Criteria andIsprivateNotEqualTo(Boolean value) {
            addCriterion("isPrivate <>", value, "isprivate");
            return (Criteria) this;
        }

        public Criteria andIsprivateGreaterThan(Boolean value) {
            addCriterion("isPrivate >", value, "isprivate");
            return (Criteria) this;
        }

        public Criteria andIsprivateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isPrivate >=", value, "isprivate");
            return (Criteria) this;
        }

        public Criteria andIsprivateLessThan(Boolean value) {
            addCriterion("isPrivate <", value, "isprivate");
            return (Criteria) this;
        }

        public Criteria andIsprivateLessThanOrEqualTo(Boolean value) {
            addCriterion("isPrivate <=", value, "isprivate");
            return (Criteria) this;
        }

        public Criteria andIsprivateIn(List<Boolean> values) {
            addCriterion("isPrivate in", values, "isprivate");
            return (Criteria) this;
        }

        public Criteria andIsprivateNotIn(List<Boolean> values) {
            addCriterion("isPrivate not in", values, "isprivate");
            return (Criteria) this;
        }

        public Criteria andIsprivateBetween(Boolean value1, Boolean value2) {
            addCriterion("isPrivate between", value1, value2, "isprivate");
            return (Criteria) this;
        }

        public Criteria andIsprivateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isPrivate not between", value1, value2, "isprivate");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("startTime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("startTime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Long value) {
            addCriterion("startTime =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Long value) {
            addCriterion("startTime <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Long value) {
            addCriterion("startTime >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Long value) {
            addCriterion("startTime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Long value) {
            addCriterion("startTime <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Long value) {
            addCriterion("startTime <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Long> values) {
            addCriterion("startTime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Long> values) {
            addCriterion("startTime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Long value1, Long value2) {
            addCriterion("startTime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Long value1, Long value2) {
            addCriterion("startTime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endTime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endTime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Long value) {
            addCriterion("endTime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Long value) {
            addCriterion("endTime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Long value) {
            addCriterion("endTime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Long value) {
            addCriterion("endTime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Long value) {
            addCriterion("endTime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Long value) {
            addCriterion("endTime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Long> values) {
            addCriterion("endTime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Long> values) {
            addCriterion("endTime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Long value1, Long value2) {
            addCriterion("endTime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Long value1, Long value2) {
            addCriterion("endTime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andMsgIsNull() {
            addCriterion("Msg is null");
            return (Criteria) this;
        }

        public Criteria andMsgIsNotNull() {
            addCriterion("Msg is not null");
            return (Criteria) this;
        }

        public Criteria andMsgEqualTo(String value) {
            addCriterion("Msg =", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotEqualTo(String value) {
            addCriterion("Msg <>", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThan(String value) {
            addCriterion("Msg >", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThanOrEqualTo(String value) {
            addCriterion("Msg >=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThan(String value) {
            addCriterion("Msg <", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThanOrEqualTo(String value) {
            addCriterion("Msg <=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLike(String value) {
            addCriterion("Msg like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotLike(String value) {
            addCriterion("Msg not like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgIn(List<String> values) {
            addCriterion("Msg in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotIn(List<String> values) {
            addCriterion("Msg not in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgBetween(String value1, String value2) {
            addCriterion("Msg between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotBetween(String value1, String value2) {
            addCriterion("Msg not between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andEndmsgIsNull() {
            addCriterion("endMsg is null");
            return (Criteria) this;
        }

        public Criteria andEndmsgIsNotNull() {
            addCriterion("endMsg is not null");
            return (Criteria) this;
        }

        public Criteria andEndmsgEqualTo(String value) {
            addCriterion("endMsg =", value, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgNotEqualTo(String value) {
            addCriterion("endMsg <>", value, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgGreaterThan(String value) {
            addCriterion("endMsg >", value, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgGreaterThanOrEqualTo(String value) {
            addCriterion("endMsg >=", value, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgLessThan(String value) {
            addCriterion("endMsg <", value, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgLessThanOrEqualTo(String value) {
            addCriterion("endMsg <=", value, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgLike(String value) {
            addCriterion("endMsg like", value, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgNotLike(String value) {
            addCriterion("endMsg not like", value, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgIn(List<String> values) {
            addCriterion("endMsg in", values, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgNotIn(List<String> values) {
            addCriterion("endMsg not in", values, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgBetween(String value1, String value2) {
            addCriterion("endMsg between", value1, value2, "endmsg");
            return (Criteria) this;
        }

        public Criteria andEndmsgNotBetween(String value1, String value2) {
            addCriterion("endMsg not between", value1, value2, "endmsg");
            return (Criteria) this;
        }

        public Criteria andRegexIsNull() {
            addCriterion("Regex is null");
            return (Criteria) this;
        }

        public Criteria andRegexIsNotNull() {
            addCriterion("Regex is not null");
            return (Criteria) this;
        }

        public Criteria andRegexEqualTo(String value) {
            addCriterion("Regex =", value, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexNotEqualTo(String value) {
            addCriterion("Regex <>", value, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexGreaterThan(String value) {
            addCriterion("Regex >", value, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexGreaterThanOrEqualTo(String value) {
            addCriterion("Regex >=", value, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexLessThan(String value) {
            addCriterion("Regex <", value, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexLessThanOrEqualTo(String value) {
            addCriterion("Regex <=", value, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexLike(String value) {
            addCriterion("Regex like", value, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexNotLike(String value) {
            addCriterion("Regex not like", value, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexIn(List<String> values) {
            addCriterion("Regex in", values, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexNotIn(List<String> values) {
            addCriterion("Regex not in", values, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexBetween(String value1, String value2) {
            addCriterion("Regex between", value1, value2, "regex");
            return (Criteria) this;
        }

        public Criteria andRegexNotBetween(String value1, String value2) {
            addCriterion("Regex not between", value1, value2, "regex");
            return (Criteria) this;
        }

        public Criteria andReplyIsNull() {
            addCriterion("Reply is null");
            return (Criteria) this;
        }

        public Criteria andReplyIsNotNull() {
            addCriterion("Reply is not null");
            return (Criteria) this;
        }

        public Criteria andReplyEqualTo(String value) {
            addCriterion("Reply =", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotEqualTo(String value) {
            addCriterion("Reply <>", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyGreaterThan(String value) {
            addCriterion("Reply >", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyGreaterThanOrEqualTo(String value) {
            addCriterion("Reply >=", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLessThan(String value) {
            addCriterion("Reply <", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLessThanOrEqualTo(String value) {
            addCriterion("Reply <=", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLike(String value) {
            addCriterion("Reply like", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotLike(String value) {
            addCriterion("Reply not like", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyIn(List<String> values) {
            addCriterion("Reply in", values, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotIn(List<String> values) {
            addCriterion("Reply not in", values, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyBetween(String value1, String value2) {
            addCriterion("Reply between", value1, value2, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotBetween(String value1, String value2) {
            addCriterion("Reply not between", value1, value2, "reply");
            return (Criteria) this;
        }

        public Criteria andRemindmsgIsNull() {
            addCriterion("remindMsg is null");
            return (Criteria) this;
        }

        public Criteria andRemindmsgIsNotNull() {
            addCriterion("remindMsg is not null");
            return (Criteria) this;
        }

        public Criteria andRemindmsgEqualTo(String value) {
            addCriterion("remindMsg =", value, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgNotEqualTo(String value) {
            addCriterion("remindMsg <>", value, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgGreaterThan(String value) {
            addCriterion("remindMsg >", value, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgGreaterThanOrEqualTo(String value) {
            addCriterion("remindMsg >=", value, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgLessThan(String value) {
            addCriterion("remindMsg <", value, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgLessThanOrEqualTo(String value) {
            addCriterion("remindMsg <=", value, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgLike(String value) {
            addCriterion("remindMsg like", value, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgNotLike(String value) {
            addCriterion("remindMsg not like", value, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgIn(List<String> values) {
            addCriterion("remindMsg in", values, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgNotIn(List<String> values) {
            addCriterion("remindMsg not in", values, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgBetween(String value1, String value2) {
            addCriterion("remindMsg between", value1, value2, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindmsgNotBetween(String value1, String value2) {
            addCriterion("remindMsg not between", value1, value2, "remindmsg");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateIsNull() {
            addCriterion("remindIsPrivate is null");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateIsNotNull() {
            addCriterion("remindIsPrivate is not null");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateEqualTo(Boolean value) {
            addCriterion("remindIsPrivate =", value, "remindisprivate");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateNotEqualTo(Boolean value) {
            addCriterion("remindIsPrivate <>", value, "remindisprivate");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateGreaterThan(Boolean value) {
            addCriterion("remindIsPrivate >", value, "remindisprivate");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("remindIsPrivate >=", value, "remindisprivate");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateLessThan(Boolean value) {
            addCriterion("remindIsPrivate <", value, "remindisprivate");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateLessThanOrEqualTo(Boolean value) {
            addCriterion("remindIsPrivate <=", value, "remindisprivate");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateIn(List<Boolean> values) {
            addCriterion("remindIsPrivate in", values, "remindisprivate");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateNotIn(List<Boolean> values) {
            addCriterion("remindIsPrivate not in", values, "remindisprivate");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateBetween(Boolean value1, Boolean value2) {
            addCriterion("remindIsPrivate between", value1, value2, "remindisprivate");
            return (Criteria) this;
        }

        public Criteria andRemindisprivateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("remindIsPrivate not between", value1, value2, "remindisprivate");
            return (Criteria) this;
        }

        public Criteria andRemindtimeIsNull() {
            addCriterion("remindTime is null");
            return (Criteria) this;
        }

        public Criteria andRemindtimeIsNotNull() {
            addCriterion("remindTime is not null");
            return (Criteria) this;
        }

        public Criteria andRemindtimeEqualTo(Long value) {
            addCriterion("remindTime =", value, "remindtime");
            return (Criteria) this;
        }

        public Criteria andRemindtimeNotEqualTo(Long value) {
            addCriterion("remindTime <>", value, "remindtime");
            return (Criteria) this;
        }

        public Criteria andRemindtimeGreaterThan(Long value) {
            addCriterion("remindTime >", value, "remindtime");
            return (Criteria) this;
        }

        public Criteria andRemindtimeGreaterThanOrEqualTo(Long value) {
            addCriterion("remindTime >=", value, "remindtime");
            return (Criteria) this;
        }

        public Criteria andRemindtimeLessThan(Long value) {
            addCriterion("remindTime <", value, "remindtime");
            return (Criteria) this;
        }

        public Criteria andRemindtimeLessThanOrEqualTo(Long value) {
            addCriterion("remindTime <=", value, "remindtime");
            return (Criteria) this;
        }

        public Criteria andRemindtimeIn(List<Long> values) {
            addCriterion("remindTime in", values, "remindtime");
            return (Criteria) this;
        }

        public Criteria andRemindtimeNotIn(List<Long> values) {
            addCriterion("remindTime not in", values, "remindtime");
            return (Criteria) this;
        }

        public Criteria andRemindtimeBetween(Long value1, Long value2) {
            addCriterion("remindTime between", value1, value2, "remindtime");
            return (Criteria) this;
        }

        public Criteria andRemindtimeNotBetween(Long value1, Long value2) {
            addCriterion("remindTime not between", value1, value2, "remindtime");
            return (Criteria) this;
        }

        public Criteria andSavemsgIsNull() {
            addCriterion("saveMsg is null");
            return (Criteria) this;
        }

        public Criteria andSavemsgIsNotNull() {
            addCriterion("saveMsg is not null");
            return (Criteria) this;
        }

        public Criteria andSavemsgEqualTo(String value) {
            addCriterion("saveMsg =", value, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgNotEqualTo(String value) {
            addCriterion("saveMsg <>", value, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgGreaterThan(String value) {
            addCriterion("saveMsg >", value, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgGreaterThanOrEqualTo(String value) {
            addCriterion("saveMsg >=", value, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgLessThan(String value) {
            addCriterion("saveMsg <", value, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgLessThanOrEqualTo(String value) {
            addCriterion("saveMsg <=", value, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgLike(String value) {
            addCriterion("saveMsg like", value, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgNotLike(String value) {
            addCriterion("saveMsg not like", value, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgIn(List<String> values) {
            addCriterion("saveMsg in", values, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgNotIn(List<String> values) {
            addCriterion("saveMsg not in", values, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgBetween(String value1, String value2) {
            addCriterion("saveMsg between", value1, value2, "savemsg");
            return (Criteria) this;
        }

        public Criteria andSavemsgNotBetween(String value1, String value2) {
            addCriterion("saveMsg not between", value1, value2, "savemsg");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNull() {
            addCriterion("groupID is null");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNotNull() {
            addCriterion("groupID is not null");
            return (Criteria) this;
        }

        public Criteria andGroupidEqualTo(String value) {
            addCriterion("groupID =", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotEqualTo(String value) {
            addCriterion("groupID <>", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThan(String value) {
            addCriterion("groupID >", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThanOrEqualTo(String value) {
            addCriterion("groupID >=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThan(String value) {
            addCriterion("groupID <", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThanOrEqualTo(String value) {
            addCriterion("groupID <=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLike(String value) {
            addCriterion("groupID like", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotLike(String value) {
            addCriterion("groupID not like", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidIn(List<String> values) {
            addCriterion("groupID in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotIn(List<String> values) {
            addCriterion("groupID not in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidBetween(String value1, String value2) {
            addCriterion("groupID between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotBetween(String value1, String value2) {
            addCriterion("groupID not between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGrouplistIsNull() {
            addCriterion("groupList is null");
            return (Criteria) this;
        }

        public Criteria andGrouplistIsNotNull() {
            addCriterion("groupList is not null");
            return (Criteria) this;
        }

        public Criteria andGrouplistEqualTo(String value) {
            addCriterion("groupList =", value, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistNotEqualTo(String value) {
            addCriterion("groupList <>", value, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistGreaterThan(String value) {
            addCriterion("groupList >", value, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistGreaterThanOrEqualTo(String value) {
            addCriterion("groupList >=", value, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistLessThan(String value) {
            addCriterion("groupList <", value, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistLessThanOrEqualTo(String value) {
            addCriterion("groupList <=", value, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistLike(String value) {
            addCriterion("groupList like", value, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistNotLike(String value) {
            addCriterion("groupList not like", value, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistIn(List<String> values) {
            addCriterion("groupList in", values, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistNotIn(List<String> values) {
            addCriterion("groupList not in", values, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistBetween(String value1, String value2) {
            addCriterion("groupList between", value1, value2, "grouplist");
            return (Criteria) this;
        }

        public Criteria andGrouplistNotBetween(String value1, String value2) {
            addCriterion("groupList not between", value1, value2, "grouplist");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 14 19:04:24 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public static class Criterion {
        private final String condition;
        private final String typeHandler;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}