package top.fluffcotton.pojo;

public class QqGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq_group.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq_group.groupList
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String grouplist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq_group.power
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Byte power;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq_group.isBan
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Boolean isban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq_group.groupName
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq_group.isRoot
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Boolean isroot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq_group.deleteTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long deletetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_group.groupID
     *
     * @return the value of qq_group.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_group.groupID
     *
     * @param groupid the value for qq_group.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_group.groupList
     *
     * @return the value of qq_group.groupList
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getGrouplist() {
        return grouplist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_group.groupList
     *
     * @param grouplist the value for qq_group.groupList
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setGrouplist(String grouplist) {
        this.grouplist = grouplist == null ? null : grouplist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_group.power
     *
     * @return the value of qq_group.power
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Byte getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_group.power
     *
     * @param power the value for qq_group.power
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setPower(Byte power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_group.isBan
     *
     * @return the value of qq_group.isBan
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Boolean getIsban() {
        return isban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_group.isBan
     *
     * @param isban the value for qq_group.isBan
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setIsban(Boolean isban) {
        this.isban = isban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_group.groupName
     *
     * @return the value of qq_group.groupName
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_group.groupName
     *
     * @param groupname the value for qq_group.groupName
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_group.isRoot
     *
     * @return the value of qq_group.isRoot
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Boolean getIsroot() {
        return isroot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_group.isRoot
     *
     * @param isroot the value for qq_group.isRoot
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setIsroot(Boolean isroot) {
        this.isroot = isroot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_group.deleteTime
     *
     * @return the value of qq_group.deleteTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getDeletetime() {
        return deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_group.deleteTime
     *
     * @param deletetime the value for qq_group.deleteTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setDeletetime(Long deletetime) {
        this.deletetime = deletetime;
    }
}