package top.fluffcotton.pojo;

public class Remindmission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.M_ID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.name
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.isPrivate
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Boolean isprivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.startTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.endTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.Msg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.status
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.groupList
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String grouplist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.isRepeat
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Boolean isrepeat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remindmission.repeatTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long repeattime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.M_ID
     *
     * @return the value of remindmission.M_ID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.M_ID
     *
     * @param mId the value for remindmission.M_ID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setmId(String mId) {
        this.mId = mId == null ? null : mId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.name
     *
     * @return the value of remindmission.name
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.name
     *
     * @param name the value for remindmission.name
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.isPrivate
     *
     * @return the value of remindmission.isPrivate
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Boolean getIsprivate() {
        return isprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.isPrivate
     *
     * @param isprivate the value for remindmission.isPrivate
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setIsprivate(Boolean isprivate) {
        this.isprivate = isprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.startTime
     *
     * @return the value of remindmission.startTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.startTime
     *
     * @param starttime the value for remindmission.startTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setStarttime(Long starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.endTime
     *
     * @return the value of remindmission.endTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.endTime
     *
     * @param endtime the value for remindmission.endTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setEndtime(Long endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.Msg
     *
     * @return the value of remindmission.Msg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.Msg
     *
     * @param msg the value for remindmission.Msg
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.groupID
     *
     * @return the value of remindmission.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.groupID
     *
     * @param groupid the value for remindmission.groupID
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.status
     *
     * @return the value of remindmission.status
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.status
     *
     * @param status the value for remindmission.status
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.groupList
     *
     * @return the value of remindmission.groupList
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getGrouplist() {
        return grouplist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.groupList
     *
     * @param grouplist the value for remindmission.groupList
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setGrouplist(String grouplist) {
        this.grouplist = grouplist == null ? null : grouplist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.isRepeat
     *
     * @return the value of remindmission.isRepeat
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Boolean getIsrepeat() {
        return isrepeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.isRepeat
     *
     * @param isrepeat the value for remindmission.isRepeat
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setIsrepeat(Boolean isrepeat) {
        this.isrepeat = isrepeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remindmission.repeatTime
     *
     * @return the value of remindmission.repeatTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getRepeattime() {
        return repeattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remindmission.repeatTime
     *
     * @param repeattime the value for remindmission.repeatTime
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setRepeattime(Long repeattime) {
        this.repeattime = repeattime;
    }
}