package top.fluffcotton.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq_openid
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String qqOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq_access_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String qqAccessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq_expires_in
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long qqExpiresIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq_refresh_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String qqRefreshToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq_access_token_time
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long qqAccessTokenTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.yb_userid
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String ybUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.yb_access_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String ybAccessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechat_openid
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String wechatOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechat_access_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String wechatAccessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechat_expires_in
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long wechatExpiresIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechat_refresh_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String wechatRefreshToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechat_access_token_time
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private Long wechatAccessTokenTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.robotQQ
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    private String robotqq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq_openid
     *
     * @return the value of user.qq_openid
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getQqOpenid() {
        return qqOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq_openid
     *
     * @param qqOpenid the value for user.qq_openid
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setQqOpenid(String qqOpenid) {
        this.qqOpenid = qqOpenid == null ? null : qqOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq_access_token
     *
     * @return the value of user.qq_access_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getQqAccessToken() {
        return qqAccessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq_access_token
     *
     * @param qqAccessToken the value for user.qq_access_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setQqAccessToken(String qqAccessToken) {
        this.qqAccessToken = qqAccessToken == null ? null : qqAccessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq_expires_in
     *
     * @return the value of user.qq_expires_in
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getQqExpiresIn() {
        return qqExpiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq_expires_in
     *
     * @param qqExpiresIn the value for user.qq_expires_in
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setQqExpiresIn(Long qqExpiresIn) {
        this.qqExpiresIn = qqExpiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq_refresh_token
     *
     * @return the value of user.qq_refresh_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getQqRefreshToken() {
        return qqRefreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq_refresh_token
     *
     * @param qqRefreshToken the value for user.qq_refresh_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setQqRefreshToken(String qqRefreshToken) {
        this.qqRefreshToken = qqRefreshToken == null ? null : qqRefreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq_access_token_time
     *
     * @return the value of user.qq_access_token_time
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getQqAccessTokenTime() {
        return qqAccessTokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq_access_token_time
     *
     * @param qqAccessTokenTime the value for user.qq_access_token_time
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setQqAccessTokenTime(Long qqAccessTokenTime) {
        this.qqAccessTokenTime = qqAccessTokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.yb_userid
     *
     * @return the value of user.yb_userid
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getYbUserid() {
        return ybUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.yb_userid
     *
     * @param ybUserid the value for user.yb_userid
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setYbUserid(String ybUserid) {
        this.ybUserid = ybUserid == null ? null : ybUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.yb_access_token
     *
     * @return the value of user.yb_access_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getYbAccessToken() {
        return ybAccessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.yb_access_token
     *
     * @param ybAccessToken the value for user.yb_access_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setYbAccessToken(String ybAccessToken) {
        this.ybAccessToken = ybAccessToken == null ? null : ybAccessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wechat_openid
     *
     * @return the value of user.wechat_openid
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getWechatOpenid() {
        return wechatOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wechat_openid
     *
     * @param wechatOpenid the value for user.wechat_openid
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setWechatOpenid(String wechatOpenid) {
        this.wechatOpenid = wechatOpenid == null ? null : wechatOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wechat_access_token
     *
     * @return the value of user.wechat_access_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getWechatAccessToken() {
        return wechatAccessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wechat_access_token
     *
     * @param wechatAccessToken the value for user.wechat_access_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setWechatAccessToken(String wechatAccessToken) {
        this.wechatAccessToken = wechatAccessToken == null ? null : wechatAccessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wechat_expires_in
     *
     * @return the value of user.wechat_expires_in
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getWechatExpiresIn() {
        return wechatExpiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wechat_expires_in
     *
     * @param wechatExpiresIn the value for user.wechat_expires_in
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setWechatExpiresIn(Long wechatExpiresIn) {
        this.wechatExpiresIn = wechatExpiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wechat_refresh_token
     *
     * @return the value of user.wechat_refresh_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getWechatRefreshToken() {
        return wechatRefreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wechat_refresh_token
     *
     * @param wechatRefreshToken the value for user.wechat_refresh_token
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setWechatRefreshToken(String wechatRefreshToken) {
        this.wechatRefreshToken = wechatRefreshToken == null ? null : wechatRefreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wechat_access_token_time
     *
     * @return the value of user.wechat_access_token_time
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Long getWechatAccessTokenTime() {
        return wechatAccessTokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wechat_access_token_time
     *
     * @param wechatAccessTokenTime the value for user.wechat_access_token_time
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setWechatAccessTokenTime(Long wechatAccessTokenTime) {
        this.wechatAccessTokenTime = wechatAccessTokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.robotQQ
     *
     * @return the value of user.robotQQ
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getRobotqq() {
        return robotqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.robotQQ
     *
     * @param robotqq the value for user.robotQQ
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setRobotqq(String robotqq) {
        this.robotqq = robotqq == null ? null : robotqq.trim();
    }
}