package top.fluffcotton.pojo;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public UserExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("qq is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("qq is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("qq =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("qq <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("qq >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("qq >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("qq <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("qq <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("qq like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("qq not like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<String> values) {
            addCriterion("qq in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<String> values) {
            addCriterion("qq not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("qq between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("qq not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqOpenidIsNull() {
            addCriterion("qq_openid is null");
            return (Criteria) this;
        }

        public Criteria andQqOpenidIsNotNull() {
            addCriterion("qq_openid is not null");
            return (Criteria) this;
        }

        public Criteria andQqOpenidEqualTo(String value) {
            addCriterion("qq_openid =", value, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidNotEqualTo(String value) {
            addCriterion("qq_openid <>", value, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidGreaterThan(String value) {
            addCriterion("qq_openid >", value, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("qq_openid >=", value, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidLessThan(String value) {
            addCriterion("qq_openid <", value, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidLessThanOrEqualTo(String value) {
            addCriterion("qq_openid <=", value, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidLike(String value) {
            addCriterion("qq_openid like", value, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidNotLike(String value) {
            addCriterion("qq_openid not like", value, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidIn(List<String> values) {
            addCriterion("qq_openid in", values, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidNotIn(List<String> values) {
            addCriterion("qq_openid not in", values, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidBetween(String value1, String value2) {
            addCriterion("qq_openid between", value1, value2, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqOpenidNotBetween(String value1, String value2) {
            addCriterion("qq_openid not between", value1, value2, "qqOpenid");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenIsNull() {
            addCriterion("qq_access_token is null");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenIsNotNull() {
            addCriterion("qq_access_token is not null");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenEqualTo(String value) {
            addCriterion("qq_access_token =", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotEqualTo(String value) {
            addCriterion("qq_access_token <>", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenGreaterThan(String value) {
            addCriterion("qq_access_token >", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("qq_access_token >=", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenLessThan(String value) {
            addCriterion("qq_access_token <", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("qq_access_token <=", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenLike(String value) {
            addCriterion("qq_access_token like", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotLike(String value) {
            addCriterion("qq_access_token not like", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenIn(List<String> values) {
            addCriterion("qq_access_token in", values, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotIn(List<String> values) {
            addCriterion("qq_access_token not in", values, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenBetween(String value1, String value2) {
            addCriterion("qq_access_token between", value1, value2, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotBetween(String value1, String value2) {
            addCriterion("qq_access_token not between", value1, value2, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInIsNull() {
            addCriterion("qq_expires_in is null");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInIsNotNull() {
            addCriterion("qq_expires_in is not null");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInEqualTo(Long value) {
            addCriterion("qq_expires_in =", value, "qqExpiresIn");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInNotEqualTo(Long value) {
            addCriterion("qq_expires_in <>", value, "qqExpiresIn");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInGreaterThan(Long value) {
            addCriterion("qq_expires_in >", value, "qqExpiresIn");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInGreaterThanOrEqualTo(Long value) {
            addCriterion("qq_expires_in >=", value, "qqExpiresIn");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInLessThan(Long value) {
            addCriterion("qq_expires_in <", value, "qqExpiresIn");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInLessThanOrEqualTo(Long value) {
            addCriterion("qq_expires_in <=", value, "qqExpiresIn");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInIn(List<Long> values) {
            addCriterion("qq_expires_in in", values, "qqExpiresIn");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInNotIn(List<Long> values) {
            addCriterion("qq_expires_in not in", values, "qqExpiresIn");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInBetween(Long value1, Long value2) {
            addCriterion("qq_expires_in between", value1, value2, "qqExpiresIn");
            return (Criteria) this;
        }

        public Criteria andQqExpiresInNotBetween(Long value1, Long value2) {
            addCriterion("qq_expires_in not between", value1, value2, "qqExpiresIn");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenIsNull() {
            addCriterion("qq_refresh_token is null");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenIsNotNull() {
            addCriterion("qq_refresh_token is not null");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenEqualTo(String value) {
            addCriterion("qq_refresh_token =", value, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenNotEqualTo(String value) {
            addCriterion("qq_refresh_token <>", value, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenGreaterThan(String value) {
            addCriterion("qq_refresh_token >", value, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenGreaterThanOrEqualTo(String value) {
            addCriterion("qq_refresh_token >=", value, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenLessThan(String value) {
            addCriterion("qq_refresh_token <", value, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenLessThanOrEqualTo(String value) {
            addCriterion("qq_refresh_token <=", value, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenLike(String value) {
            addCriterion("qq_refresh_token like", value, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenNotLike(String value) {
            addCriterion("qq_refresh_token not like", value, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenIn(List<String> values) {
            addCriterion("qq_refresh_token in", values, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenNotIn(List<String> values) {
            addCriterion("qq_refresh_token not in", values, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenBetween(String value1, String value2) {
            addCriterion("qq_refresh_token between", value1, value2, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqRefreshTokenNotBetween(String value1, String value2) {
            addCriterion("qq_refresh_token not between", value1, value2, "qqRefreshToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeIsNull() {
            addCriterion("qq_access_token_time is null");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeIsNotNull() {
            addCriterion("qq_access_token_time is not null");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeEqualTo(Long value) {
            addCriterion("qq_access_token_time =", value, "qqAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeNotEqualTo(Long value) {
            addCriterion("qq_access_token_time <>", value, "qqAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeGreaterThan(Long value) {
            addCriterion("qq_access_token_time >", value, "qqAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("qq_access_token_time >=", value, "qqAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeLessThan(Long value) {
            addCriterion("qq_access_token_time <", value, "qqAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeLessThanOrEqualTo(Long value) {
            addCriterion("qq_access_token_time <=", value, "qqAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeIn(List<Long> values) {
            addCriterion("qq_access_token_time in", values, "qqAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeNotIn(List<Long> values) {
            addCriterion("qq_access_token_time not in", values, "qqAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeBetween(Long value1, Long value2) {
            addCriterion("qq_access_token_time between", value1, value2, "qqAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenTimeNotBetween(Long value1, Long value2) {
            addCriterion("qq_access_token_time not between", value1, value2, "qqAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andYbUseridIsNull() {
            addCriterion("yb_userid is null");
            return (Criteria) this;
        }

        public Criteria andYbUseridIsNotNull() {
            addCriterion("yb_userid is not null");
            return (Criteria) this;
        }

        public Criteria andYbUseridEqualTo(String value) {
            addCriterion("yb_userid =", value, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridNotEqualTo(String value) {
            addCriterion("yb_userid <>", value, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridGreaterThan(String value) {
            addCriterion("yb_userid >", value, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridGreaterThanOrEqualTo(String value) {
            addCriterion("yb_userid >=", value, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridLessThan(String value) {
            addCriterion("yb_userid <", value, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridLessThanOrEqualTo(String value) {
            addCriterion("yb_userid <=", value, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridLike(String value) {
            addCriterion("yb_userid like", value, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridNotLike(String value) {
            addCriterion("yb_userid not like", value, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridIn(List<String> values) {
            addCriterion("yb_userid in", values, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridNotIn(List<String> values) {
            addCriterion("yb_userid not in", values, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridBetween(String value1, String value2) {
            addCriterion("yb_userid between", value1, value2, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbUseridNotBetween(String value1, String value2) {
            addCriterion("yb_userid not between", value1, value2, "ybUserid");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenIsNull() {
            addCriterion("yb_access_token is null");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenIsNotNull() {
            addCriterion("yb_access_token is not null");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenEqualTo(String value) {
            addCriterion("yb_access_token =", value, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenNotEqualTo(String value) {
            addCriterion("yb_access_token <>", value, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenGreaterThan(String value) {
            addCriterion("yb_access_token >", value, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("yb_access_token >=", value, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenLessThan(String value) {
            addCriterion("yb_access_token <", value, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("yb_access_token <=", value, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenLike(String value) {
            addCriterion("yb_access_token like", value, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenNotLike(String value) {
            addCriterion("yb_access_token not like", value, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenIn(List<String> values) {
            addCriterion("yb_access_token in", values, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenNotIn(List<String> values) {
            addCriterion("yb_access_token not in", values, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenBetween(String value1, String value2) {
            addCriterion("yb_access_token between", value1, value2, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andYbAccessTokenNotBetween(String value1, String value2) {
            addCriterion("yb_access_token not between", value1, value2, "ybAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidIsNull() {
            addCriterion("wechat_openid is null");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidIsNotNull() {
            addCriterion("wechat_openid is not null");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidEqualTo(String value) {
            addCriterion("wechat_openid =", value, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidNotEqualTo(String value) {
            addCriterion("wechat_openid <>", value, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidGreaterThan(String value) {
            addCriterion("wechat_openid >", value, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_openid >=", value, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidLessThan(String value) {
            addCriterion("wechat_openid <", value, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidLessThanOrEqualTo(String value) {
            addCriterion("wechat_openid <=", value, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidLike(String value) {
            addCriterion("wechat_openid like", value, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidNotLike(String value) {
            addCriterion("wechat_openid not like", value, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidIn(List<String> values) {
            addCriterion("wechat_openid in", values, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidNotIn(List<String> values) {
            addCriterion("wechat_openid not in", values, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidBetween(String value1, String value2) {
            addCriterion("wechat_openid between", value1, value2, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatOpenidNotBetween(String value1, String value2) {
            addCriterion("wechat_openid not between", value1, value2, "wechatOpenid");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenIsNull() {
            addCriterion("wechat_access_token is null");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenIsNotNull() {
            addCriterion("wechat_access_token is not null");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenEqualTo(String value) {
            addCriterion("wechat_access_token =", value, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenNotEqualTo(String value) {
            addCriterion("wechat_access_token <>", value, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenGreaterThan(String value) {
            addCriterion("wechat_access_token >", value, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_access_token >=", value, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenLessThan(String value) {
            addCriterion("wechat_access_token <", value, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("wechat_access_token <=", value, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenLike(String value) {
            addCriterion("wechat_access_token like", value, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenNotLike(String value) {
            addCriterion("wechat_access_token not like", value, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenIn(List<String> values) {
            addCriterion("wechat_access_token in", values, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenNotIn(List<String> values) {
            addCriterion("wechat_access_token not in", values, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenBetween(String value1, String value2) {
            addCriterion("wechat_access_token between", value1, value2, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenNotBetween(String value1, String value2) {
            addCriterion("wechat_access_token not between", value1, value2, "wechatAccessToken");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInIsNull() {
            addCriterion("wechat_expires_in is null");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInIsNotNull() {
            addCriterion("wechat_expires_in is not null");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInEqualTo(Long value) {
            addCriterion("wechat_expires_in =", value, "wechatExpiresIn");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInNotEqualTo(Long value) {
            addCriterion("wechat_expires_in <>", value, "wechatExpiresIn");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInGreaterThan(Long value) {
            addCriterion("wechat_expires_in >", value, "wechatExpiresIn");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInGreaterThanOrEqualTo(Long value) {
            addCriterion("wechat_expires_in >=", value, "wechatExpiresIn");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInLessThan(Long value) {
            addCriterion("wechat_expires_in <", value, "wechatExpiresIn");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInLessThanOrEqualTo(Long value) {
            addCriterion("wechat_expires_in <=", value, "wechatExpiresIn");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInIn(List<Long> values) {
            addCriterion("wechat_expires_in in", values, "wechatExpiresIn");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInNotIn(List<Long> values) {
            addCriterion("wechat_expires_in not in", values, "wechatExpiresIn");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInBetween(Long value1, Long value2) {
            addCriterion("wechat_expires_in between", value1, value2, "wechatExpiresIn");
            return (Criteria) this;
        }

        public Criteria andWechatExpiresInNotBetween(Long value1, Long value2) {
            addCriterion("wechat_expires_in not between", value1, value2, "wechatExpiresIn");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenIsNull() {
            addCriterion("wechat_refresh_token is null");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenIsNotNull() {
            addCriterion("wechat_refresh_token is not null");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenEqualTo(String value) {
            addCriterion("wechat_refresh_token =", value, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenNotEqualTo(String value) {
            addCriterion("wechat_refresh_token <>", value, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenGreaterThan(String value) {
            addCriterion("wechat_refresh_token >", value, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_refresh_token >=", value, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenLessThan(String value) {
            addCriterion("wechat_refresh_token <", value, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenLessThanOrEqualTo(String value) {
            addCriterion("wechat_refresh_token <=", value, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenLike(String value) {
            addCriterion("wechat_refresh_token like", value, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenNotLike(String value) {
            addCriterion("wechat_refresh_token not like", value, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenIn(List<String> values) {
            addCriterion("wechat_refresh_token in", values, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenNotIn(List<String> values) {
            addCriterion("wechat_refresh_token not in", values, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenBetween(String value1, String value2) {
            addCriterion("wechat_refresh_token between", value1, value2, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatRefreshTokenNotBetween(String value1, String value2) {
            addCriterion("wechat_refresh_token not between", value1, value2, "wechatRefreshToken");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeIsNull() {
            addCriterion("wechat_access_token_time is null");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeIsNotNull() {
            addCriterion("wechat_access_token_time is not null");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeEqualTo(Long value) {
            addCriterion("wechat_access_token_time =", value, "wechatAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeNotEqualTo(Long value) {
            addCriterion("wechat_access_token_time <>", value, "wechatAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeGreaterThan(Long value) {
            addCriterion("wechat_access_token_time >", value, "wechatAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("wechat_access_token_time >=", value, "wechatAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeLessThan(Long value) {
            addCriterion("wechat_access_token_time <", value, "wechatAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeLessThanOrEqualTo(Long value) {
            addCriterion("wechat_access_token_time <=", value, "wechatAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeIn(List<Long> values) {
            addCriterion("wechat_access_token_time in", values, "wechatAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeNotIn(List<Long> values) {
            addCriterion("wechat_access_token_time not in", values, "wechatAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeBetween(Long value1, Long value2) {
            addCriterion("wechat_access_token_time between", value1, value2, "wechatAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andWechatAccessTokenTimeNotBetween(Long value1, Long value2) {
            addCriterion("wechat_access_token_time not between", value1, value2, "wechatAccessTokenTime");
            return (Criteria) this;
        }

        public Criteria andRobotqqIsNull() {
            addCriterion("robotQQ is null");
            return (Criteria) this;
        }

        public Criteria andRobotqqIsNotNull() {
            addCriterion("robotQQ is not null");
            return (Criteria) this;
        }

        public Criteria andRobotqqEqualTo(String value) {
            addCriterion("robotQQ =", value, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqNotEqualTo(String value) {
            addCriterion("robotQQ <>", value, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqGreaterThan(String value) {
            addCriterion("robotQQ >", value, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqGreaterThanOrEqualTo(String value) {
            addCriterion("robotQQ >=", value, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqLessThan(String value) {
            addCriterion("robotQQ <", value, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqLessThanOrEqualTo(String value) {
            addCriterion("robotQQ <=", value, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqLike(String value) {
            addCriterion("robotQQ like", value, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqNotLike(String value) {
            addCriterion("robotQQ not like", value, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqIn(List<String> values) {
            addCriterion("robotQQ in", values, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqNotIn(List<String> values) {
            addCriterion("robotQQ not in", values, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqBetween(String value1, String value2) {
            addCriterion("robotQQ between", value1, value2, "robotqq");
            return (Criteria) this;
        }

        public Criteria andRobotqqNotBetween(String value1, String value2) {
            addCriterion("robotQQ not between", value1, value2, "robotqq");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 14 19:04:24 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    public static class Criterion {
        private final String condition;
        private final String typeHandler;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}