package top.fluffcotton.mapper;

import org.apache.ibatis.annotations.Param;
import top.fluffcotton.pojo.Command;
import top.fluffcotton.pojo.CommandExample;

import java.util.List;

public interface CommandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    long countByExample(CommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int deleteByExample(CommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int deleteByPrimaryKey(String groupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int insert(Command record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int insertSelective(Command record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    List<Command> selectByExampleWithBLOBs(CommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    List<Command> selectByExample(CommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    Command selectByPrimaryKey(String groupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Command record, @Param("example") CommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Command record, @Param("example") CommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByExample(@Param("record") Command record, @Param("example") CommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByPrimaryKeySelective(Command record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table command
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Command record);
}