package top.fluffcotton.mapper;

import org.apache.ibatis.annotations.Param;
import top.fluffcotton.pojo.FolderGroup;
import top.fluffcotton.pojo.FolderGroupExample;

import java.util.List;

public interface FolderGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    long countByExample(FolderGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int deleteByExample(FolderGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int deleteByPrimaryKey(String fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int insert(FolderGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int insertSelective(FolderGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    List<FolderGroup> selectByExample(FolderGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    FolderGroup selectByPrimaryKey(String fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") FolderGroup record, @Param("example") FolderGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByExample(@Param("record") FolderGroup record, @Param("example") FolderGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByPrimaryKeySelective(FolderGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder_group
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByPrimaryKey(FolderGroup record);
}