package top.fluffcotton.mapper;

import org.apache.ibatis.annotations.Param;
import top.fluffcotton.pojo.Folder;
import top.fluffcotton.pojo.FolderExample;

import java.util.List;

public interface FolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    long countByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int deleteByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int deleteByPrimaryKey(String fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int insert(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int insertSelective(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    List<Folder> selectByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    Folder selectByPrimaryKey(String fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Folder record, @Param("example") FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByExample(@Param("record") Folder record, @Param("example") FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByPrimaryKeySelective(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByPrimaryKey(Folder record);
}