package top.fluffcotton.mapper;

import org.apache.ibatis.annotations.Param;
import top.fluffcotton.pojo.Remindmission;
import top.fluffcotton.pojo.RemindmissionExample;

import java.util.List;

public interface RemindmissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    long countByExample(RemindmissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int deleteByExample(RemindmissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int deleteByPrimaryKey(String mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int insert(Remindmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int insertSelective(Remindmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    List<Remindmission> selectByExample(RemindmissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    Remindmission selectByPrimaryKey(String mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Remindmission record, @Param("example") RemindmissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByExample(@Param("record") Remindmission record, @Param("example") RemindmissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByPrimaryKeySelective(Remindmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remindmission
     *
     * @mbg.generated Mon Sep 14 19:04:24 CST 2020
     */
    int updateByPrimaryKey(Remindmission record);
}